### ISSUE TITLE
A question on responsive design

### ISSUE THREAD

**Issue by jidemusty** [ireade/ama#12]
I have always wanted to ask this question following my visit to bitsofcode and I was amazed on how it fits different screens and how responsive it is. Do you design for different screen sizes or use media queries and I know you don't use bootstrap(got to know this while you were live on codeclass or so I can't remember the name). I am a backend developer but I have taken interest in frontend development with angular/vuejs. Thank you as you answer this.

**Comment by ireade** [comment]
Hi @jidemusty !

I user media queries to adapt the design for different screen sizes. For this blog, I created the Desktop design using Sketch, and from that I had an idea of how I wanted everything to fit on Mobile. When writing the CSS, I use a "mobile first" method, which means I have the default styles the mobile styles, then use media queries to alter the layout for larger screens. 

For example, these styles on the `.site__header` element:

```css
.site__header {
  margin-bottom: 40px; 
}
@media screen and (min-width: 500px) {
  .site__header {
    margin-bottom: 70px; 
  }
}
```
